"""MLflow pyfunc wrapper for the Monte Carlo GBM model.

Wraps the GBM parameters (mu, sigma, seed) into a proper mlflow.pyfunc model
so the Inference Service can load it via mlflow.pyfunc.load_model() and call
predict() on it — exactly like any other MLflow model.

Artifact layout (stored under the 'model/' artifact path in the MLflow run):
    model/
        MLmodel          ← generated by mlflow.pyfunc.save_model()
        python_model.pkl ← pickled MonteCarloModel instance
        params.json      ← human-readable GBM params for inspection

Input to predict():
    pandas.DataFrame with columns:
        - n_simulations  (int,   default 10_000)
        - horizon_days   (int,   default 1)
        - alpha          (float, default 0.99)

Output of predict():
    pandas.DataFrame with columns:
        - var        (float) — positive loss number
        - cvar       (float) — positive loss number
        - volatility (float) — annualised
        - method     (str)   — always "montecarlo"
"""
from __future__ import annotations

import logging
from typing import Any

import mlflow.pyfunc
import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# Default simulation parameters (used when not provided in the input DataFrame)
_DEFAULT_N_SIMS = 10_000
_DEFAULT_HORIZON = 1
_DEFAULT_ALPHA = 0.99


class MonteCarloModel(mlflow.pyfunc.PythonModel):
    """MLflow pyfunc model that runs GBM Monte Carlo simulation.

    The model stores the fitted GBM parameters (mu, sigma) estimated from
    historical portfolio returns at training time. At inference time it
    re-runs the simulation with the stored parameters.

    Attributes:
        mu:    Daily GBM drift (log-return mean + 0.5*sigma^2).
        sigma: Daily GBM volatility (std of log-returns).
        seed:  Random seed for reproducibility (None = random).
    """

    def __init__(self, mu: float, sigma: float, seed: int | None = 42) -> None:
        self.mu = mu
        self.sigma = sigma
        self.seed = seed

    # ------------------------------------------------------------------
    # mlflow.pyfunc.PythonModel interface
    # ------------------------------------------------------------------

    def predict(self, context: Any, model_input: pd.DataFrame) -> pd.DataFrame:
        """Run Monte Carlo simulation and return risk metrics.

        Args:
            context:     MLflow context (unused).
            model_input: DataFrame with optional columns:
                         n_simulations, horizon_days, alpha.
                         Missing columns use defaults.

        Returns:
            DataFrame with one row per input row containing:
            var, cvar, volatility, method.
        """
        results = []
        for _, row in model_input.iterrows():
            n_sims = int(row.get("n_simulations", _DEFAULT_N_SIMS))
            horizon = int(row.get("horizon_days", _DEFAULT_HORIZON))
            alpha = float(row.get("alpha", _DEFAULT_ALPHA))

            var, cvar, vol = self._run_simulation(n_sims, horizon, alpha)
            results.append({
                "var": var,
                "cvar": cvar,
                "volatility": vol,
                "method": "montecarlo",
            })

        return pd.DataFrame(results)

    # ------------------------------------------------------------------
    # Internal simulation
    # ------------------------------------------------------------------

    def _run_simulation(
        self,
        n_simulations: int,
        horizon_days: int,
        alpha: float,
    ) -> tuple[float, float, float]:
        """Run GBM simulation and return (var, cvar, annualised_vol)."""
        rng = np.random.default_rng(self.seed)

        dt = 1.0
        drift = (self.mu - 0.5 * self.sigma ** 2) * dt
        diffusion = self.sigma * np.sqrt(dt)

        # Shape: (n_simulations, horizon_days)
        daily_log_returns = rng.normal(
            loc=drift, scale=diffusion, size=(n_simulations, horizon_days)
        )
        total_log_returns = daily_log_returns.sum(axis=1)
        simulated = np.exp(total_log_returns) - 1.0  # simple returns

        var_quantile = np.quantile(simulated, 1.0 - alpha)
        var = float(-var_quantile)
        tail = simulated[simulated <= var_quantile]
        cvar = float(-tail.mean()) if len(tail) > 0 else var
        vol = float(np.std(simulated, ddof=1) * np.sqrt(252 / horizon_days))

        logger.debug(
            "MC simulation: n=%d  horizon=%d  alpha=%.4f  VaR=%.6f  CVaR=%.6f",
            n_simulations, horizon_days, alpha, var, cvar,
        )
        return var, cvar, vol

    # ------------------------------------------------------------------
    # Convenience: build from historical returns
    # ------------------------------------------------------------------

    @classmethod
    def from_returns(
        cls,
        returns: np.ndarray,
        seed: int | None = 42,
    ) -> "MonteCarloModel":
        """Estimate GBM parameters from historical returns and create a model instance.

        Args:
            returns: 1-D array of daily portfolio returns.
            seed:    Random seed for reproducibility.

        Returns:
            MonteCarloModel with fitted mu and sigma.
        """
        sigma = float(np.std(returns, ddof=1))
        mu = float(np.mean(returns)) + 0.5 * sigma ** 2
        logger.info("MC pyfunc: estimated mu=%.6f  sigma=%.6f from %d observations", mu, sigma, len(returns))
        return cls(mu=mu, sigma=sigma, seed=seed)
